name: Pull request
# This workflow is triggered on pushes to the repository.
on: [pull-request]

jobs:
  build:
    # Job name is Greeting
    name: Build and test
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '10']
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm run test-coverage
      - run: npm run build
      - run: npm run e2e-ci
